### ISSUE TITLE
旁路由模式下报错？

### ISSUE THREAD

**Issue by ilihu** [Sherlockouo/music#132]
```
$ ./R3PLAYX-2.7.5-linux-x86_64.AppImage
20:50:34 info › 

   _  __   __     _     ____                    __  ___                    _        
  | |/ /  / /_   (_)   / __/   __  __          /  |/  /  __  __   _____   (_)  _____
  |   /  / __/  / /   / /_    / / / /         / /|_/ /  / / / /  / ___/  / /  / ___/ 
 /   |  / /_   / /   / __/   / /_/ /         / /  / /  / /_/ /  (__  )  / /  / /__  
/_/|_|  \__/  /_/   /_/      \__, /         /_/  /_/   \__,_/  /____/  /_/   \___/  
                            /____/

20:50:34 info › [logger] logger initialized
20:50:34 info › [electron] utils.ts
20:50:34 info › [preload] dirname /tmp/.mount_R3PLAYtXZ4Ys/resources/app.asar/main
20:50:34 info › [preload] userData path: /home/lihu/.config/R3PLAYX
20:50:34 info › [sentry] sentry initializing
20:50:34 info › [sentry] sentry initialized
20:50:34 info › [electron] db.ts
20:50:34 info › [db] Initializing database...
20:50:34 info › [db] Initializing database tables...
20:50:34 info › [db] Database tables initialized.
20:50:34 info › [db] Migrating database..
20:50:34 info › [db] Database migrated.
20:50:34 info › [db] Database initialized.
20:50:34 info › [electron] cache.ts
20:50:34 info › [electron] store.ts
20:50:34 info › [electron] menu.ts
20:50:34 info › [electron] ipcMain.ts
20:50:34 info › [electron] tray.ts
20:50:34 info › [electron] windowsTaskbar.ts
20:50:34 info › [electron] appServer/routes/r3play/appleMusic.ts
20:50:35 info › [electron] appServer/routes/r3play/audio.ts
20:50:35 info › [electron] appServer/appServer.ts
20:50:35 info › [electron] index.ts
20:50:35 info › [index] Main process start
20:50:35 info › [index] App ready
20:50:36 info › [appServer] http server listening on port 42710
20:50:36 info › checkForUpdates
20:50:36 info › Checking for update
[278622:0316/205036.900151:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
20:50:37 debug › [server] Audio cache hit 1870225884
20:50:37 info › {
  status: 502,
  body: {
    code: 502,
    msg: {
      message: 'unable to verify the first certificate',
      name: 'Error',
      stack: 'Error: unable to verify the first certificate\n' +
        '    at AxiosError.from (/tmp/.mount_R3PLAYtXZ4Ys/resources/app.asar/node_modules/axios/dist/node/axios.cjs:836:14)\n' +
        '    at RedirectableRequest.handleRequestError (/tmp/.mount_R3PLAYtXZ4Ys/resources/app.asar/node_modules/axios/dist/node/axios.cjs:3010:25)\n' +
        '    at RedirectableRequest.emit (node:events:517:28)\n' +
        '    at RedirectableRequest.emit (node:domain:489:12)\n' +
        '    at eventHandlers.<computed> (/tmp/.mount_R3PLAYtXZ4Ys/resources/app.asar/node_modules/follow-redirects/index.js:14:24)\n' +
        '    at ClientRequest.emit (node:events:529:35)\n' +
        '    at ClientRequest.emit (node:domain:489:12)\n' +
        '    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n' +
        '    at TLSSocket.emit (node:events:517:28)\n' +
        '    at TLSSocket.emit (node:domain:489:12)',
      config: [Object],
      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
      status: null
    }
  },
  cookie: []
}
20:50:39 info › Update for version 2.7.5 is not available (latest version: 2.7.5, downgrade is disallowed).
```

系统是Ubuntu 22.04， 旁路由上跑了openclash， 运行了一个vless代理。

网络切成主路由就正常了，如何让使用旁路由代理的人正常运行该项目？

**Comment by ilihu** [comment]
```
export NODE_TLS_REJECT_UNAUTHORIZED=0 
```
运行之前加入该环境变量解决了"UNABLE_TO_VERIFY_LEAF_SIGNATURE"的问题，如果可以的话，希望通过程序本身来实现

**Comment by Sherlockouo** [comment]
额，你会写吗？可以提个pr
