### ISSUE TITLE
[Bugs] ArchLinux 运行报错

### ISSUE THREAD

**Issue by zxp19821005** [Sherlockouo/music#58]
如题。我已经将其移植到了ArchLinux的AUR：https://aur.archlinux.org/packages/r3playx-bin
目前基本可以正常运行，但是存在报错信息。
### 环境信息
OS：EndeavourOS 6.1.62-1-lts
DE: Cinnamon 5.8.0
Electron: 23
Version: 2.7.0
### 报错信息
```
error › Error: Cannot find module '/usr/lib/electron23/resources/bin/better_sqlite3.node'
Require stack:
- /usr/lib/r3playx/app.asar/node_modules/better-sqlite3/lib/database.js
- /usr/lib/r3playx/app.asar/node_modules/better-sqlite3/lib/index.js
- /usr/lib/r3playx/app.asar/main/index.js
- /usr/lib/electron23/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1002:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109734)
    at Module._load (node:internal/modules/cjs/loader:848:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Database (/usr/lib/r3playx/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at new M$ (/usr/lib/r3playx/app.asar/main/index.js:572:7251)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:9787)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
```
我已经将`better_sqlite3.node`安装到了`/usr/lib/r3playx`，并且在脚本中指定了`PATH`，但是仍然报错。
这个我怀疑是调用的时候写的路径有问题。
```
10:36:07 info › [index] App ready
10:36:07 info › [appServer] http server listening on port 42710
10:36:08 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:08 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:169892)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:16 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:16 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:170439)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:16 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:16 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:170439)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:16 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:16 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:170439)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:16 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:16 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:170439)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:16 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:16 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:170439)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:36:20 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
10:36:20 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at M$.upsert (/usr/lib/r3playx/app.asar/main/index.js:572:9215)
    at mU.set (/usr/lib/r3playx/app.asar/main/index.js:572:169892)
    at Object.<anonymous> (/usr/lib/r3playx/app.asar/main/index.js:572:188651)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
剩下的这些错误就不知道是什么意思了，还得麻烦大神再看看。

**Comment by Sherlockouo** [comment]
应该是链接数据的问题，虽然不影响使用(数据库起缓存作用)，我后面排查下问题。

**Comment by Sherlockouo** [comment]
另外可以check下你在 安装依赖时，是否下载better-sqlite3.node 并成功编译

**Comment by zxp19821005** [comment]
我是直接下载的AppImage包，然后解压缩的，没有编译。

**Comment by lu0se** [comment]
这个并不是bug,运行appimage是没问题的
解压缩后采用了系统的electron
无论是process.resourcesPath electron/electron#31121
还是代码中都是根据electron的可执行文件来判断resource目录的，
[db.ts中寻找sqlite代码](https://github.com/Sherlockouo/music/blob/7501518ed65c9abca017d969f2c64f53b9133269/packages/desktop/main/db.ts#L106C3-L120C4)
在解压缩打包后采用系统的electron后会根据系统elecron来寻找resource目录

**Comment by zxp19821005** [comment]
不知道能否采用相对路径之类的呢？比如说`../node-modules`之类的？

**Comment by lu0se** [comment]
@zxp19821005 
直接将db.ts中的nativeBinding和getBinpath注释掉改为
```
this.sqlite = new SQLite3(this.dbFilePath)
```
，你的aur打包就不会出现问题了，但是不知道是否影响其他系统的打包使用
![图片](https://github.com/Sherlockouo/music/assets/55630902/308db503-2ed5-40ae-8e9d-e83552e846f7)

**Comment by zxp19821005** [comment]
@lu0se 改这个好像不行，我编译的时候报错了：
```
$ makepkg -f
==> 正在创建软件包：r3playx-git 2.7.1.r10.g81d34dc-1 (2023年11月23日 星期四 13时36分37秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 正在升级 r3playx git 仓库...
  -> 找到 r3playx.sh
==> 正在验证 source 文件，使用sha256sums...
    r3playx ... 已跳过
    r3playx.sh ... 通过
==> 正在释放源码...
  -> 正在建立 r3playx git 仓库的拷贝...
重置分支 'makepkg'
==> 正在开始 pkgver()...
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
Scope: all 4 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1866
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  GET https://registry.npmjs.org/NeteaseCloudMusicApi/-/NeteaseCloudMusicApi-4.13.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Downloading registry.npmjs.org/electron-winstaller/5.1.0: 8.97 MB/8.97 MB, done
Downloading registry.npmjs.org/turbo-linux-64/1.10.16: 19.81 MB/19.81 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.38: 14.91 MB/14.91 MB, done
Downloading registry.npmjs.org/typescript/4.7.4: 11.70 MB/11.70 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.38: 14.77 MB/14.77 MB, done
Progress: resolved 0, reused 716, downloaded 846, added 1863
Progress: resolved 0, reused 716, downloaded 848, added 1866, done
node_modules/@prisma/engines: Running postinstall script, done in 8.7s
node_modules/better-sqlite3: Running install script, done in 3.8s
node_modules/fast-folder-size: Running postinstall script, done in 172ms
node_modules/electron-winstaller: Running install script, done in 79ms
node_modules/lzma-native: Running install script, done in 100ms
node_modules/prisma: Running preinstall script, done in 97ms
node_modules/esbuild: Running postinstall script, done in 98ms
node_modules/@swc/core: Running postinstall script, done in 80ms
node_modules/vite/node_modules/esbuild: Running postinstall script, done in 83ms
node_modules/speaker: Running install script, failed in 1.3s (skipped as optional)
packages/desktop/node_modules/esbuild: Running postinstall script, done in 99ms
packages/server/node_modules/vite/node_modules/esbuild: Running postinstall script, done in 92ms
node_modules/electron: Running postinstall script, done in 19.9s
node_modules/@prisma/client: Running postinstall script, done in 385ms
packages/desktop postinstall$ tsx scripts/build.sqlite3.ts
│ (node:200265) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
│ (Use `node --trace-warnings ...` to show where the warning was created)
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ projectDir=/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playxs.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ binDir=/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/tmp/bin/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ Creating dist/binary directory: /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/tmp/bin
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ electronModuleVersion=113risma Client in your code. Reference: https://pris.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ Downloading x64 binary...risma Client in your code. Reference: https://pris.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ Downloading arm64 binary...sma Client in your code. Reference: https://pris.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ Download failed! Skip download.Client in your code. Reference: https://pris.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
│ Building for arm64...ng Prisma Client in your code. Reference: https://pris.ly/d/client
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
[1 lines collapsed]
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()gesis run.
│ ```
└─ Done in 782ms
. install$ turbo run post-install --parallel --no-cache
│ • Packages in scope: desktop, server, web
│ • Running post-install in 3 packagesis run.
│ • Remote caching disabled
│ Build succeededccessful, 0 total
└─ Running...
packages/server postinstall$ prisma generate
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (5.1.1 | library) to ./../../node_modules/@prisma/client in 61ms
└─ Done in 1m 8.5st using Prisma Client in your code. Reference: https://pris.ly/d/client
│ projectDir=/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx
│ binDir=/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/tmp/bin
│ Creating dist/binary directory: /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/tmp/bin
│ electronModuleVersion=113
│ Downloading x64 binary...
│ Downloading arm64 binary...tall --parallel --no-cache
│ Download failed! Skip download.erver, web
│ Building for arm64...
│ Build succeeded
│ copy /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/node_modules/better-sqlite3/build/Release/better_sqlite3.node to /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/tmp/bin/bet…
│ Cached:    0 cached, 0 total
│   Time:    69ms 
│ No tasks were executed as part of this run.
└─ Done in 162ms
Done in 2m 23.2s

> r3playx@2.7.1 package /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx
> turbo run build && pnpm run --filter desktop package

• Packages in scope: desktop, server, web
• Running build in 3 packages
• Remote caching disabled
desktop:build: cache bypass, force executing 187469a321d0a778
server:build: cache bypass, force executing 8ae473a48113faa5
web:build: cache bypass, force executing 18263b6449a424a9
server:build: 
server:build: > server@2.7.1 build /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/packages/server
server:build: > tsc
server:build: 
web:build: 
web:build: > web@2.7.1 build /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/packages/web
web:build: > vite build
web:build: 
desktop:build: 
desktop:build: > desktop@2.7.1 build /home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/packages/desktop
desktop:build: > tsx scripts/build.main.ts
desktop:build: 
desktop:build: (node:201024) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
desktop:build: (Use `node --trace-warnings ...` to show where the warning was created)
web:build: vite v4.5.0 building for production...
web:build: transforming...
web:build: Browserslist: caniuse-lite is outdated. Please run:
web:build:   npx update-browserslist-db@latest
web:build:   Why you should do it regularly: https://github.com/browserslist/update-db#readme
desktop:build: {}
desktop:build: - [script/build.main.ts] Main Process Building...
desktop:build: [script/build.main.ts] Main Process Build Succeeded.
server:build: ../desktop/main/db.ts:7:1 - error TS6133: 'isProd' is declared but its value is never read.
server:build: 
server:build: 7 import { isProd } from './env'
server:build:   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server:build: 
server:build: ../desktop/main/db.ts:10:1 - error TS6133: 'os' is declared but its value is never read.
server:build: 
server:build: 10 import os from 'os'
server:build:    ~~~~~~~~~~~~~~~~~~~
server:build: 
server:build: 
server:build: Found 2 errors in the same file, starting at: ../desktop/main/db.ts:7
server:build: 
server:build:  ELIFECYCLE  Command failed with exit code 1.
server:build: ERROR: command finished with error: command (/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/packages/server) pnpm run build exited (1)
server#build: command (/home/zxp-endeavouros/.cache/paru/clone/r3playx-git/src/r3playx/packages/server) pnpm run build exited (1)

 Tasks:    1 successful, 3 total
Cached:    0 cached, 3 total
  Time:    2.655s 
Failed:    server#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
```
build部分代码：
```
build() {
    gendesk -q -f -n --categories "AudioVideo" --name="${_pkgname}" --exec="${pkgname%-git}"
    cd "${srcdir}/${pkgname%-git}"
    sed -e '106,120d' \
        -e '92,94d' \
        -e '91i\    this.sqlite = new SQLite3(this.dbFilePath)' \
        -i packages/desktop/main/db.ts
    pnpm install --no-frozen-lockfile
    pnpm run package
}
```

**Comment by zxp19821005** [comment]
@lu0se 按照你的方法进行了修改，运行后不显示界面，系统栏图标正常。
`PKGBUILD`文件如下：
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname=r3playx-git
_pkgname=R3PLAYX
pkgver=2.7.1.r11.g4320ede
pkgrel=1
pkgdesc="A music player forked from YesPlayMusic。高颜值的第三方网易云播放器，支持 Windows / macOS / Linux"
arch=('x86_64')
url="https://github.com/Sherlockouo/music"
license=('AGPL3')
conflicts=("${pkgname%-git}" "yesplaymusic" "r3play")
provides=("yesplaymusic")
depends=(
    'electron23'
    'hicolor-icon-theme'
    'python'
)
makedepends=(
    'gendesk'
    'git'
    'nvm'
    'npm'
    'pnpm>=7.20.0'
    'make'
    'gcc'
)
source=(
    "${pkgname%-git}"::"git+${url}.git"
    "${pkgname%-git}.sh"
)
sha256sums=('SKIP'
            'f3ecacd977fa9a41efe35eb2e228f0d8e1dc71bca33002d4838bf41df6438055')
pkgver() {
    cd "${srcdir}/${pkgname%-git}"
    git describe --long --tags --exclude='*[a-z][a-z]*' | sed -E 's/^v//;s/([^-]*-g)/r\1/;s/-/./g'
}
_ensure_local_nvm() {
    export NVM_DIR="${srcdir}/.nvm"
    source /usr/share/nvm/init-nvm.sh || [[ $? != 1 ]]
    nvm install 18
    nvm use 18
}
build() {
    _ensure_local_nvm
    gendesk -q -f -n --categories "AudioVideo" --name="${_pkgname}" --exec="${pkgname%-git}"
    cd "${srcdir}/${pkgname%-git}"
    sed -e '106,120d' \
        -e '92,94d' \
        -e '91i\    this.sqlite = new SQLite3(this.dbFilePath)' \
        -e '10d' \
        -e '7d' \
        -i packages/desktop/main/db.ts
    npm i prisma fastify-cli turbo tsx electron-builder@23.6.0 -g
    pnpm install
    pnpm package
}
package() {
    install -Dm755 "${srcdir}/${pkgname%-git}.sh" "${pkgdir}/usr/bin/${pkgname%-git}"
    install -Dm644 "${srcdir}/${pkgname%-git}/packages/desktop/release/linux-unpacked/resources/app.asar" -t "${pkgdir}/usr/lib/${pkgname%-git}"
    cp -r "${srcdir}/${pkgname%-git}/packages/desktop/release/linux-unpacked/resources/"{app.asar.unpacked,bin} "${pkgdir}/usr/lib/${pkgname%-git}"
    for _icons in 16x16 24x24 32x32 64x64 256x256 512x512 1024x1024;do
        install -Dm644 "${srcdir}/${pkgname%-git}/packages/desktop/build/icons/${_icons}.png" \
            "${pkgdir}/usr/share/icons/hicolor/${_icons}/apps/${pkgname%-git}.png"
    done
    install -Dm644 "${srcdir}/${pkgname%-git}.desktop" -t "${pkgdir}/usr/share/applications"
}
```
`r3playx.sh`内容如下：
```
#!/bin/bash
_ELECTRON=/usr/bin/electron23
APPDIR="/usr/lib/r3playx"
export PATH="${APPDIR}:${APPDIR}/bin:${PATH}"
#export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"
_ASAR="${APPDIR}/app.asar"
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    exec ${_ELECTRON} ${_ASAR} "$@"
else
    exec ${_ELECTRON} ${_ASAR} --no-sandbox "$@"
fi
```

**Comment by zxp19821005** [comment]
@lu0se 谢谢大佬指点，目前我在AUR上新移植了一个包 [r3playx-git](https://aur.archlinux.org/packages/r3playx-git)

**Comment by Discreater** [comment]
目前最新版本的 r3playx-bin 依旧会报错，并且无法播放歌曲。参考 https://aur.archlinux.org/packages/r3playx-bin 中的链接better_sqlite3.node 文件到对应 electron 版本目录之后才能正常使用。

这个 issue 是否应该再次开启？

**Comment by zxp19821005** [comment]
不需要了，谢谢！ @Discreater
