### ISSUE TITLE
Linux版本无法播放音乐

### ISSUE THREAD

**Issue by End782** [Sherlockouo/music#8]
发行版: openSUSE Tumbleweed
问题: 无法播放任何音乐, 也不会显示播放状态栏

控制台截图:
![Screenshot_20230913_104303](https://github.com/Sherlockouo/music/assets/57061809/abd4a4aa-5666-47fb-a1bf-7d2b41223c4b)

部分log(因为后续的报错信息重复):
```
[2023-09-13 10:31:56.673] [info]  

██╗   ██╗███████╗███████╗██████╗ ██╗      █████╗ ██╗   ██╗███╗   ███╗██╗   ██╗███████╗██╗ ██████╗
╚██╗ ██╔╝██╔════╝██╔════╝██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝████╗ ████║██║   ██║██╔════╝██║██╔════╝
 ╚████╔╝ █████╗  ███████╗██████╔╝██║     ███████║ ╚████╔╝ ██╔████╔██║██║   ██║███████╗██║██║     
  ╚██╔╝  ██╔══╝  ╚════██║██╔═══╝ ██║     ██╔══██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║╚════██║██║██║     
   ██║   ███████╗███████║██║     ███████╗██║  ██║   ██║   ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗
   ╚═╝   ╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝

[2023-09-13 10:31:56.681] [info]  [logger] logger initialized
[2023-09-13 10:31:56.681] [info]  [electron] utils.ts
[2023-09-13 10:31:56.682] [info]  [preload] dirname /tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main
[2023-09-13 10:31:56.683] [info]  [preload] userData path: /home/solitaryanimal/.config/R3PLAYX
[2023-09-13 10:31:56.722] [info]  [sentry] sentry initializing
[2023-09-13 10:31:56.741] [info]  [sentry] sentry initialized
[2023-09-13 10:31:56.748] [info]  [electron] db.ts
[2023-09-13 10:31:56.748] [info]  [db] Initializing database...
[2023-09-13 10:31:56.756] [error] [db] Database initialization failed.
[2023-09-13 10:31:56.757] [error] Error: The module '/tmp/.mount_R3PLAYmTmFu5/resources/bin/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 103. This version of Node.js requires
NODE_MODULE_VERSION 113. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Database (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at new NO (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:7251)
[2023-09-13 10:31:56.760] [info]  [electron] cache.ts
[2023-09-13 10:31:56.760] [info]  [electron] ipcMain.ts
[2023-09-13 10:31:56.761] [info]  [electron] tray.ts
[2023-09-13 10:31:56.761] [info]  [electron] windowsTaskbar.ts
[2023-09-13 10:31:56.761] [info]  [electron] menu.ts
[2023-09-13 10:31:56.774] [info]  [electron] store.ts
[2023-09-13 10:31:56.809] [info]  [electron] appServer/routes/r3play/appleMusic.ts
[2023-09-13 10:31:57.108] [info]  [electron] appServer/routes/netease.ts
[2023-09-13 10:31:57.131] [info]  [electron] appServer/routes/r3play/audio.ts
[2023-09-13 10:31:57.177] [info]  [electron] appServer/appServer.ts
[2023-09-13 10:31:57.177] [info]  [electron] index.ts
[2023-09-13 10:31:57.177] [info]  [index] Main process start
[2023-09-13 10:31:57.331] [info]  [index] App ready
[2023-09-13 10:31:57.483] [info]  [appServer] http server listening on port 42710
[2023-09-13 10:31:57.483] [info]  [initUnlockSubProcess] Initializing initUnlockSubProcess...
[2023-09-13 10:31:57.552] [info]  [UNLOCK] 服务器运行在 http://localhost:30003/
[2023-09-13 10:31:58.322] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2023-09-13 10:31:58.322] [error] TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-13 10:31:58.331] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2023-09-13 10:31:58.331] [error] TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-13 10:31:58.334] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2023-09-13 10:31:58.334] [error] TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-13 10:31:58.459] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2023-09-13 10:31:58.459] [error] TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_R3PLAYmTmFu5/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Sherlockouo** [comment]
OK，看来Linux还是有些区别，也有可能是我打包平台的问题

**Comment by End782** [comment]
> OK，看来Linux还是有些区别，也有可能是我打包平台的问题

在[这里](https://github.com/qier222/YesPlayMusic/releases/tag/v2.0.0-alpha-2)下载的版本可以正常播放

**Comment by lu0se** [comment]
相同问题，日志：
```
/opt/appimages/r3play.AppImage
17:33:38 info ›

██╗   ██╗███████╗███████╗██████╗ ██╗      █████╗ ██╗   ██╗███╗   ███╗██╗   ██╗███████╗██╗ ██████╗
╚██╗ ██╔╝██╔════╝██╔════╝██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝████╗ ████║██║   ██║██╔════╝██║██╔════╝
 ╚████╔╝ █████╗  ███████╗██████╔╝██║     ███████║ ╚████╔╝ ██╔████╔██║██║   ██║███████╗██║██║
  ╚██╔╝  ██╔══╝  ╚════██║██╔═══╝ ██║     ██╔══██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║╚════██║██║██║
   ██║   ███████╗███████║██║     ███████╗██║  ██║   ██║   ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗
   ╚═╝   ╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝

17:33:38 info › [logger] logger initialized
17:33:38 info › [electron] utils.ts
17:33:38 info › [preload] dirname /tmp/.mount_r3playmd4QX7/resources/app.asar/main
17:33:38 info › [preload] userData path: /home/lu0se/.config/R3PLAYX
17:33:38 info › [sentry] sentry initializing
17:33:38 info › [sentry] sentry initialized
17:33:38 info › [electron] db.ts
17:33:38 info › [db] Initializing database...
17:33:38 error › [db] Database initialization failed.
17:33:38 error › Error: The module '/tmp/.mount_r3playmd4QX7/resources/bin/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 103. This version of Node.js requires
NODE_MODULE_VERSION 113. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Database (/tmp/.mount_r3playmd4QX7/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at new NO (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:7251)
17:33:38 info › [electron] cache.ts
17:33:38 info › [electron] ipcMain.ts
17:33:38 info › [electron] tray.ts
17:33:38 info › [electron] windowsTaskbar.ts
17:33:38 info › [electron] menu.ts
17:33:38 info › [electron] store.ts
17:33:39 info › [electron] appServer/routes/r3play/appleMusic.ts
17:33:39 info › [electron] appServer/routes/netease.ts
17:33:39 info › [electron] appServer/routes/r3play/audio.ts
17:33:39 info › [electron] appServer/appServer.ts
17:33:39 info › [electron] index.ts
17:33:39 info › [index] Main process start
17:33:40 info › [index] App ready
17:33:40 info › [appServer] http server listening on port 42710
17:33:40 info › [initUnlockSubProcess] Initializing initUnlockSubProcess...
17:33:40 info › [UNLOCK] 服务器运行在 http://localhost:30003/
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170844)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:42 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:42 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:43 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:43 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:44 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:44 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:45 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:45 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:46 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:46 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:46 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:46 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:46 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:46 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2940:0917/173348.920827:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[2940:0917/173348.937803:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:33:54 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:54 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2940:0917/173356.052224:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
17:33:58 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:33:58 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170844)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:00 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:00 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:00 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:00 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:00 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:00 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170844)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:01 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:01 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:01 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:01 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:04 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:04 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:04 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:04 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:170319)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:34:04 warn › This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
17:34:04 error › TypeError: Cannot read properties of undefined (reading 'prepare')
    at NO.upsert (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:9215)
    at BL.set (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:169892)
    at Object.<anonymous> (/tmp/.mount_r3playmd4QX7/resources/app.asar/main/index.js:501:182722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Sherlockouo** [comment]
重新打包上传了，重新去 release 下载试试。 kali上是可以打开的。
<img width="1308" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/5fac8cd5-1d0c-4bac-8caf-292643bb2c77">

**Comment by Sherlockouo** [comment]
重新上传了，去release重新下载试试 
<img width="1308" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/02117699-80e4-499d-afd7-d364751bd516">

**Comment by End782** [comment]
> 重新上传了，去release重新下载试试 <img alt="image" width="1308" src="https://user-images.githubusercontent.com/34598208/268727756-02117699-80e4-499d-afd7-d364751bd516.png">

能够正常使用了, 感谢
