### ISSUE TITLE
docker 部署 报错

### ISSUE THREAD

**Issue by HuaGCS** [Sherlockouo/music#89]

**Comment by HuaGCS** [comment]
镜像版本：最新镜像
触发：docker启动后网页点击任意需跟server交互操作
server报错如下：
SqliteError: no such table: AccountData
    at Database.prepare (/app/packages/server/node_modules/.pnpm/better-sqlite3@8.5.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at DB.upsert (/app/packages/server/src/utils/db.js:101:28)
    at Cache.set (/app/packages/server/src/utils/cache.js:50:25)
    at Object.<anonymous> (/app/packages/server/src/routes/netease/netease.js:24:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}

**Comment by Sherlockouo** [comment]
最新版本修复这个问题啦

**Comment by HuaGCS** [comment]
好嘞 我去试试

**Comment by Huijiyingyingying** [comment]
> 最新版本修复这个问题啦

新版本仍然存在这个问题

SqliteError: table Artist has 5 columns but 3 values were supplied
    at Database.prepare (/app/packages/server/node_modules/.pnpm/better-sqlite3@9.2.2/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at DB.upsert (/app/packages/server/src/utils/db.js:101:28)
    at Cache.set (/app/packages/server/src/utils/cache.js:103:25)
    at Object.<anonymous> (/app/packages/server/src/routes/netease/netease.js:24:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}

**Comment by IXIXVI** [comment]
同样有这个问题,导致r3playx-backend频繁奔溃

**Comment by IXIXVI** [comment]
同样有这个问题,导致r3playx-backend频繁奔溃

stderr: SqliteError: table Artist has 5 columns but 3 values were supplied
stderr:     at Database.prepare (/app/packages/server/node_modules/.pnpm/better-sqlite3@9.2.2/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
stderr:     at DB.upsert (/app/packages/server/src/utils/db.js:101:28)
stderr:     at Cache.set (/app/packages/server/src/utils/cache.js:103:25)
stderr:     at Object.<anonymous> (/app/packages/server/src/routes/netease/netease.js:24:33)
stderr:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
stderr:   code: 'SQLITE_ERROR'

**Comment by Sherlockouo** [comment]
OK，这部分问题应该是在prisma，稍后解决了再通知

**Comment by Leon19960120** [comment]
群晖部署没出现问题，docker 网络是否可以使用host模式？

**Comment by matrixnobody** [comment]
> 同样有这个问题,导致r3playx-backend频繁奔溃
> 
> stderr: SqliteError: table Artist has 5 columns but 3 values were supplied stderr: at Database.prepare (/app/packages/server/node_modules/.pnpm/better-sqlite3@9.2.2/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21) stderr: at DB.upsert (/app/packages/server/src/utils/db.js:101:28) stderr: at Cache.set (/app/packages/server/src/utils/cache.js:103:25) stderr: at Object. (/app/packages/server/src/routes/netease/netease.js:24:33) stderr: at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { stderr: code: 'SQLITE_ERROR'

遇到了同样的问题

**Comment by friddle** [comment]
目测还是有同样的问题。。。
